theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left


#theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,fontsizeselect,|,forecolor,backcolor"
theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,forecolor,backcolor"


